# SPDX-FileCopyrightText: 2025 City of Tampere
#
# SPDX-License-Identifier: LGPL-2.1-or-later
FROM node:20.11-bookworm

ARG USER_ID=1000
ARG GROUP_ID=1000

RUN userdel -rf $(id -nu $USER_ID)
RUN groupadd -g $GROUP_ID devuser && \
    useradd -m -u $USER_ID -g devuser devuser

RUN mkdir -p /app/.yarn && chown devuser: /app /app/.yarn
RUN corepack enable

USER devuser
WORKDIR /app
