spring:
  main:
    banner-mode: "off"
  application:
    name: "oppivelvollisuus-service"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    type: "com.zaxxer.hikari.HikariDataSource"
    url: "jdbc:postgresql://localhost:5432/oppivelvollisuus"
    username: "oppivelvollisuus"
    password: "postgres"

  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "10MB"
  sql:
    init:
      continue-on-error: false
      encoding: "UTF-8"
