# SPDX-FileCopyrightText: 2023-2024 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

app:
  jwt:
    public_keys_url: classpath:local-development/jwks.json

spring:
  datasource:
    # url: "jdbc:postgresql://db:5432/oppivelvollisuus"
    # TODO: The below line has to be modified to use db to instead of localhost when in docker-compose
    # dev env (like above comment). Please see application-compose.yml. Need to implement automation to
    # switch spring boot profile to use that one when running in docker-compose
    url: "jdbc:postgresql://localhost:5432/oppivelvollisuus"
    username: "oppivelvollisuus"
    password: "postgres"
