app:
  jwt:
    public_keys_url: classpath:local-development/jwks.json

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/oppivelvollisuus"
    username: "oppivelvollisuus"
    password: "postgres"
