version: '3.5'

services:
  service:
    build:
      context: ../service/
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -server -Djava.security.egd=file:/dev/./urandom -Xms1024m -Xss512k -Xmx1024m -XX:TieredStopAtLevel=1
      SPRING_DATASOURCE_URL: jdbc:postgresql://oppivelvollisuus-db:5432/oppivelvollisuus
      SPRING_DATASOURCE_USERNAME: oppivelvollisuus
      SPRING_DATASOURCE_PASSWORD: postgres

  api-gateway:
    build:
      context: ../api-gateway/
    ports:
      - "3000:3000"
    environment:
      SERVICE_URL: "http://service:8080"
